
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ExternalLink, Eye } from "lucide-react";

export const ShowcaseGallery = () => {
  const apps = [
    {
      title: "TaskFlow Pro",
      description: "Project management with team collaboration",
      image: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=400&h=250&fit=crop",
      category: "Productivity",
      views: "2.3k",
      color: "bg-blue-500"
    },
    {
      title: "EcommerceHub",
      description: "Modern online store with payment integration",
      image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&h=250&fit=crop",
      category: "E-commerce",
      views: "4.1k",
      color: "bg-green-500"
    },
    {
      title: "FinanceTracker",
      description: "Personal finance management dashboard",
      image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=250&fit=crop",
      category: "Finance",
      views: "1.8k",
      color: "bg-purple-500"
    },
    {
      title: "FitnessPal",
      description: "Workout tracking and nutrition planning",
      image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=250&fit=crop",
      category: "Health",
      views: "3.2k",
      color: "bg-red-500"
    },
    {
      title: "LearnHub",
      description: "Online learning platform with video courses",
      image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=400&h=250&fit=crop",
      category: "Education",
      views: "5.7k",
      color: "bg-indigo-500"
    },
    {
      title: "EventPlanner",
      description: "Event management and ticketing system",
      image: "https://images.unsplash.com/photo-1511578314322-379afb476865?w=400&h=250&fit=crop",
      category: "Events",
      views: "2.9k",
      color: "bg-orange-500"
    }
  ];

  return (
    <section className="py-24 px-6 bg-white">
      <div className="max-w-7xl mx-auto">
        <div className="text-center mb-16">
          <Badge variant="secondary" className="mb-4">
            App Gallery
          </Badge>
          <h2 className="text-4xl font-bold tracking-tight mb-6">
            Apps built with CodeCraft
          </h2>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Explore real applications generated by our AI. Each one built in minutes, not months.
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8 mb-12">
          {apps.map((app, index) => (
            <Card key={index} className="group hover:shadow-lg transition-all duration-300 hover:-translate-y-1 overflow-hidden">
              <div className="relative">
                <img 
                  src={app.image} 
                  alt={app.title}
                  className="w-full h-48 object-cover group-hover:scale-105 transition-transform duration-300"
                />
                <div className="absolute inset-0 bg-black/20 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center justify-center">
                  <Button size="sm" variant="secondary" className="gap-2">
                    <Eye className="w-4 h-4" />
                    Preview
                  </Button>
                </div>
                <Badge className={`absolute top-3 left-3 ${app.color} text-white`}>
                  {app.category}
                </Badge>
              </div>
              
              <CardContent className="p-6">
                <div className="flex items-start justify-between mb-2">
                  <h3 className="font-semibold text-lg">{app.title}</h3>
                  <ExternalLink className="w-4 h-4 text-muted-foreground group-hover:text-orange-500 transition-colors" />
                </div>
                <p className="text-muted-foreground text-sm mb-4">
                  {app.description}
                </p>
                <div className="flex items-center justify-between">
                  <span className="text-xs text-muted-foreground flex items-center gap-1">
                    <Eye className="w-3 h-3" />
                    {app.views} views
                  </span>
                  <Button variant="ghost" size="sm">
                    View Details
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        <div className="text-center">
          <Button variant="outline" size="lg">
            View All Apps
          </Button>
        </div>
      </div>
    </section>
  );
};
